baseurl = "/"
languageCode = "en-us"
title = "Raoul Rodriguez"
theme = "hugo-theme-casper"
disqusShortname = "spf13"
# Enable Google Analytics by inserting your tracking code
googleAnalytics = ""
# Define how many posts should appear on a site
paginate = 10
canonifyurls = true

[params]
  description = "Mary Kate's boyfriend"
  cover = "images/cover.jpg"
  author = "Raoul J. Rodriguez"
  authorlocation = "New Jersey/York, USA"
  authorwebsite = "raoulj.io"
  bio= "Electrical Engineering undergraduate student at Princeton University"
  logo = "images/logo.png"
  googleAnalyticsUserID = "UA-79101-12"
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  RSSLink = ""
  githubName = "raoulj"
  twitterName = "vjeantet"
  # facebookName = ""
  # linkedinName = ""
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = true
  [params.social]
    twitter = "your_twitter"
